beta stabilized

diff --git a/contrib/debian/tor2web.init b/contrib/debian/tor2web.init
--- a/contrib/debian/tor2web.init
+++ b/contrib/debian/tor2web.init
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 
 ### BEGIN INIT INFO
 # startup script for Ubuntu and Debian Linux servers
@@ -18,21 +18,21 @@
 # Description:       This file starts up the tor2web server.
 ### END INIT INFO
 
-# Authors: Arturo Filasto' <art@globaleaks.org>
-#          Giovanni Pellerano <evilaliv3@globaleaks.org>
+# Authors: Arturo Filasto' <art@Tor2web.org>
+#          Giovanni Pellerano <evilaliv3@Tor2web.org>
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 NAME=tor2web
-SCRIPTNAME=/etc/init.d/$NAME
-DAEMON=/usr/local/bin/twistd
+DAEMON=twistd
+DAEMON_ENV=/home/tor2web/t2wenv/bin/activate
 DAEMON_DIR=/home/tor2web/Tor2web-3.0
-DEAMON_ENV=${DAEMON_DIR}/t2wenv/bin/activate
-DAEMON_PIDFILE=tor2web.pid
+DAEMON_PIDFILE=${DAEMON_DIR}/tor2web.pid
 DAEMON_USER=tor2web
-DAEMON_ARGS="-y /home/tor2web/Tor2web-3.0/run.py --pidfile ${DAEMON_PIDFILE} --uid ${DAEMON_USER} --gid ${DAEMON_USER}"
+DAEMON_ARGS="--pidfile ${DAEMON_PIDFILE} --uid ${DAEMON_USER} --gid ${DAEMON_USER} -y ${DAEMON_DIR}/t2w.py"
 
-# Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
+NAME=$(basename $(readlink -nf $0))
+
+SCRIPTNAME=$0
 
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
@@ -44,6 +44,7 @@ DAEMON_ARGS="-y /home/tor2web/Tor2web-3.0/run.py --pidfile ${DAEMON_PIDFILE} --u
 # Depend on lsb-base (>= 3.2-14) to ensure that this file is present
 # and status_of_proc is working.
 . /lib/lsb/init-functions
+
 
 # Let's try to figure our some sane defaults:
 if [ -r /proc/sys/fs/file-max ]; then
@@ -71,95 +72,77 @@ else
         MAX_FILEDESCRIPTORS=8192
 fi
 
-. ${DAEMON_ENV}
-
-#
-# Function that starts the daemon/service
-#
-
-do_tor_start()
+do_setup_env()
 {
-    echo "Checking Tor Status..."
-    /etc/init.d/tor status
-    RETVAL=$?
-    if [ $RETVAL -ne 0 ]; then
-        echo "Starting Tor..."
-        /etc/init.d/tor start
-        echo "started."
+    if [[ $EUID -ne 0 ]]; then
+       log_failure_msg "Error: Tor2web init script must be run as root"
+       log_end_msg 1
+       exit 1
+    fi
+
+    if [ ! -d ${DAEMON_DIR} ]
+    then
+        log_failure_msg "unexistent DAEMON_DIR: ${DEAMON_DIR}"
+        log_end_msg 1
+        exit 1
+    fi
+
+    if [ ! -f ${DAEMON_ENV} ]
+    then
+        log_failure_msg "invalid DAEMON_ENV: ${DAEMON_ENV}"
+        log_end_msg 1
+        exit 1
+    fi
+
+    . ${DAEMON_ENV}
+
+    DAEMON=`which twistd`
+    if [ ! ${DAEMON} ]; then
+        log_end_msg 1 "twistd is not installed"
+        exit 1
     fi
 }
 
 do_t2w_start()
 {
+    do_setup_env
+
     if [ -n "$MAX_FILEDESCRIPTORS" ]; then
-        echo -n "Raising maximum number of filedescriptors (ulimit -n) to $MAX_FILEDESCRIPTORS"
-        if ulimit -n "$MAX_FILEDESCRIPTORS" ; then
-            echo "."
-        else
-            echo ": FAILED."
-        fi
+        ulimit -n "$MAX_FILEDESCRIPTORS"
     fi
 
     # Check to see if the daemon is already running.
-    echo "Starting Tor2web..."
-    start-stop-daemon --start --quiet --pidfile ${DAEMON_DIR}/${DAEMON_PIDFILE} \
+    start-stop-daemon --start --quiet --pidfile ${DAEMON_PIDFILE} \
         --exec $DAEMON --chdir $DAEMON_DIR -- $DAEMON_ARGS
     RETVAL=$?
     if [ $RETVAL -eq 1 ]; then
-        echo "already running"
-        return 1
+        log_end_msg 1 "already running"
+        exit 1
     fi
 
-    if [ $RETVAL -eq 255 ]; then
-        echo "couldn't start"
-        return 2
+    if [ $RETVAL -ne 0 ]; then
+        log_end_msg 1 "couldn't start"
+        exit 1
     fi
-    echo "started."
-}
-
-do_start()
-{
-    do_tor_start
-    do_t2w_start
-}
-
-#
-# Function that stops the daemon/service
-#
-do_tor_stop()
-{
-    echo "Stopping Tor..."
-    /etc/init.d/tor stop
-    echo "stopped."
 }
 
 do_t2w_stop()
 {
-    # Return
-    #   0 if daemon has been stopped
-    #   1 if daemon was already stopped
-    #   2 if daemon could not be stopped
-    #   other if a failure occurred
+    do_setup_env
 
-    echo "Stopping Tor2web..."
-    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile ${DAEMON_DIR}/${DAEMON_PIDFILE}
-    RETVAL=$?
-    if [ $RETVAL -eq 1 ]; then
-        echo "not running"
-    else
-        echo "stopped."
-    fi
+    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile ${DAEMON_PIDFILE}
+}
 
-    # Many daemons don't delete their pidfiles when they exit.
-    rm -f ${DAEMON_DIR}/${DAEMON_PIDFILE}
-
-    return "$RETVAL"
+do_start()
+{
+    /etc/init.d/tor start
+    do_t2w_start
 }
 
 do_stop()
 {
     do_t2w_stop
-    do_tor_stop
+    /etc/init.d/tor stop
 }
 
 #
@@ -167,67 +150,56 @@ do_stop()
 #
 do_restart() {
     do_t2w_stop
-    do_tor_start
+    /etc/init.d/tor restart
     do_t2w_start
-    return 0
 }
 
 #
 # Function that queries the status of the daemon/service
 #
-do_status()
-{
-    # Return
-    #   0 if daemon is responding and OK
-    #   1 if daemon is not responding, but PIDFILE exists
-    #   2 if daemon is not responding, but LOCKFILE exists
-    #   3 if deamon is not running
-    #   4 if daemon status is unknown
-
-    # Check to see if the daemon is already running.
-    start-stop-daemon --stop --test --quiet --pidfile ${DAEMON_DIR}/${DAEMON_PIDFILE} \
-        && echo "Tor2web running OK." && return 0
-    [ -f ${DAEMON_DIR}/${DAEMON_PIDFILE} ] && echo "Tor2web not responding, but PIDFILE exists." && return 1
-    echo "Tor2web is not running"
-    return 3
-}
 
 case "$1" in
   start)
+  	log_action_begin_msg "Starting Tor2web" "tor2web"
 	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
 	do_start
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
+    log_action_end_msg 0
+    exit 0
 	;;
   stop)
+  	log_action_begin_msg "Stopping Tor2web" "tor2web"
 	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
 	do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
+    log_action_end_msg 0
+    exit 0
+    ;;
   status)
-       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-       ;;
-  #reload|force-reload)
-	#
-	# If do_reload() is not implemented then leave this commented out
-	# and leave 'force-reload' as an alias for 'restart'.
-	#
-	#log_daemon_msg "Reloading $DESC" "$NAME"
-	#do_reload
-	#log_end_msg $?
-	#;;
+    if test ! -r $(dirname ${DAEMON_PIDFILE}); then
+        log_failure_msg "cannot read PID file ${DAEMON_PIDFILE}"
+        exit 4
+    fi
+    pid=`cat ${DAEMON_PIDFILE} 2>/dev/null` || true
+    if test ! -f ${DAEMON_PIDFILE} -o -z "$pid"; then
+        log_failure_msg "Tor2web is not running"
+        exit 3
+    fi
+    if ps "$pid" >/dev/null 2>&1; then
+        log_success_msg "Tor2web is running"
+        exit 0
+    else
+        log_failure_msg "Tor2web is not running"
+        exit 1
+    fi
+    ;;
   restart|force-reload)
 	#
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
 	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
+	log_action_begin_msg "Restarting Tor2web" "tor2web"
 	do_restart
+    log_action_end_msg 0
+    exit 0
 	;;
   *)
 	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
